"""tenants personas scope_attestations

Revision ID: 382a602a156b
Revises: dd86529079db
Create Date: 2026-04-24 02:25:43.335237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382a602a156b'
down_revision: Union[str, Sequence[str], None] = 'dd86529079db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', name='pk_personas')
    )
    op.create_table('scope_attestations',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('no_phi', sa.Boolean(), nullable=False),
    sa.Column('no_payment_data', sa.Boolean(), nullable=False),
    sa.Column('no_minors', sa.Boolean(), nullable=False),
    sa.Column('no_eu_uk_residents', sa.Boolean(), nullable=False),
    sa.Column('no_sensitive_categories', sa.Boolean(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_country', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', name='pk_scope_attestations')
    )
    op.create_table('tenants',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tos_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name='pk_tenants')
    )
    # ### end Alembic commands ###

    # DIR-2.3 + DIR-11.1: enable + force RLS + tenant_isolation policy on the 3 new tables
    for t in ("tenants", "personas", "scope_attestations"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {t}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
        """)

    # Grant DML to ai_hive_app (the non-superuser role created in dd86529079db)
    for t in ("tenants", "personas", "scope_attestations"):
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO ai_hive_app;")


def downgrade() -> None:
    """Downgrade schema."""
    for t in ("tenants", "personas", "scope_attestations"):
        op.execute(f"REVOKE ALL ON {t} FROM ai_hive_app;")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {t};")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_table('scope_attestations')
    op.drop_table('personas')
    # ### end Alembic commands ###
