"""initial schema with RLS

Revision ID: 5db854d514f2
Revises: 
Create Date: 2026-04-21 21:25:07.234898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5db854d514f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biography',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_biography')
    )
    op.create_index('ix_biography_fields_gin', 'biography', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('experiences',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_experiences')
    )
    op.create_index('ix_experiences_fields_gin', 'experiences', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('preferences',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_preferences')
    )
    op.create_index('ix_preferences_fields_gin', 'preferences', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('psychometrics',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_psychometrics')
    )
    op.create_index('ix_psychometrics_fields_gin', 'psychometrics', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('social_circle',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_social_circle')
    )
    op.create_index('ix_social_circle_fields_gin', 'social_circle', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('wal',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('op', sa.Enum('add', 'edit', 'delete', 'tombstone', name='wal_op'), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=False),
    sa.Column('user_initiated', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'seq', name='pk_wal')
    )
    op.create_table('work',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'fact_id', name='pk_work')
    )
    op.create_index('ix_work_fields_gin', 'work', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    # ### end Alembic commands ###

    # DIR-2.3 + DIR-11.1: enable RLS + tenant policy on every domain table + WAL
    for table_name in ("biography", "experiences", "preferences",
                       "social_circle", "work", "psychometrics", "wal"):
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table_name}
            USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
        """)

    # DIR-2.2: functional B-tree on hot extracted sub-fields per domain
    op.execute(
        "CREATE INDEX ix_biography_fields_institution "
        "ON biography (((fields->>'institution')));"
    )
    op.execute(
        "CREATE INDEX ix_work_fields_employer "
        "ON work (((fields->>'employer')));"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # DIR-2.2: drop functional B-tree indexes added in upgrade()
    op.execute("DROP INDEX IF EXISTS ix_biography_fields_institution;")
    op.execute("DROP INDEX IF EXISTS ix_work_fields_employer;")

    for table_name in ("biography", "experiences", "preferences",
                       "social_circle", "work", "psychometrics", "wal"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table_name};")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_fields_gin', table_name='work', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('work')
    op.drop_table('wal')
    op.drop_index('ix_social_circle_fields_gin', table_name='social_circle', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('social_circle')
    op.drop_index('ix_psychometrics_fields_gin', table_name='psychometrics', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('psychometrics')
    op.drop_index('ix_preferences_fields_gin', table_name='preferences', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('preferences')
    op.drop_index('ix_experiences_fields_gin', table_name='experiences', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('experiences')
    op.drop_index('ix_biography_fields_gin', table_name='biography', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_table('biography')
    # ### end Alembic commands ###

    # DIR-2.7 / Alembic-autogen quirk: SQLAlchemy Enum column does NOT auto-drop
    # the named PG type on table drop. Explicit DROP TYPE keeps downgrade idempotent.
    op.execute("DROP TYPE IF EXISTS wal_op;")

