"""ingest_jobs pending_facts

Revision ID: dfc7bc40b15f
Revises: 382a602a156b
Create Date: 2026-04-25 17:01:33.847618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfc7bc40b15f'
down_revision: Union[str, Sequence[str], None] = '382a602a156b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='ingest_job_status'), server_default='PENDING', nullable=False),
    sa.Column('domain_status', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'job_id', name='pk_ingest_jobs')
    )
    op.create_table('pending_facts',
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('persona_id', sa.String(length=26), nullable=False),
    sa.Column('pending_fact_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'persona_id', 'pending_fact_id', name='pk_pending_facts')
    )
    op.create_index('ix_pending_facts_job', 'pending_facts', ['tenant_id', 'job_id'], unique=False)
    op.create_index('ix_pending_facts_source_hash', 'pending_facts', ['tenant_id', 'persona_id', 'source_hash'], unique=False)
    # ### end Alembic commands ###

    # Enable RLS and create tenant isolation policies
    for t in ("ingest_jobs", "pending_facts"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY;")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {t}
            USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid);
        """)
    for t in ("ingest_jobs", "pending_facts"):
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO ai_hive_app;")


def downgrade() -> None:
    """Downgrade schema."""
    # Revoke RLS and drop tables
    for t in ("ingest_jobs", "pending_facts"):
        op.execute(f"REVOKE ALL ON {t} FROM ai_hive_app;")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {t};")
        op.execute(f"ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {t} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_facts_source_hash', table_name='pending_facts')
    op.drop_index('ix_pending_facts_job', table_name='pending_facts')
    op.drop_table('pending_facts')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###

    # Drop ENUM type
    op.execute("DROP TYPE IF EXISTS ingest_job_status;")
